version: '3.8'
services:
    mongodb:
        image: mongo:latest
        container_name: nest-cnode-mongodb
        hostname: mongodb
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
        volumes:
            - ./.docker/mongo_data:/data/db
            # - ./init.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
        restart: always
